### ISSUE TITLE
Add a license to the repo?

### ISSUE THREAD

**Issue by rana-ian-intel** [polyse/logDb#5]
Hi,

Thank you for writing logdb.
Would you add a license to logdb?
That would allow me to see if I can use it.
I happen to be looking for [Apache License 2.0](https://spdx.org/licenses/Apache-2.0.html) or [MIT License](https://spdx.org/licenses/MIT.html).

Thank you,

Rana

**Comment by rana-ian-intel** [comment]
Thank you!

**Comment by senyast4745** [comment]
If it's not a secret, how are you going to use this database?)

**Comment by senyast4745** [comment]
* adapter

**Comment by senyasdt** [comment]
I' added licence! Welcome to contribute!
